use UNIVER

--ex1--
select AUDITORIUM.AUDITORIUM_NAME, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
	from AUDITORIUM_TYPE inner join AUDITORIUM
	on AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE;

--ex2--
select AUDITORIUM_TYPE.AUDITORIUM_TYPENAME, AUDITORIUM.AUDITORIUM_NAME
	from AUDITORIUM_TYPE inner join AUDITORIUM
	on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%';

--ex3--
select FACULTY.FACULTY as Факультет, PULPIT.PULPIT as Кафедра, PROFESSION.PROFESSION as Специальность,SUBJECT.SUBJECT as Дисциплина,STUDENT.NAME as Студент,
	case
        when PROGRESS.NOTE = 6 then 'шесть'
        when PROGRESS.NOTE = 7 then 'семь'
        when PROGRESS.NOTE = 8 then 'восемь'
        else 'другая'
    end as Оценки
	from PROGRESS inner join STUDENT
	on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		inner join PROFESSION on GROUPS.PROFESSION= PROFESSION.PROFESSION
	inner join SUBJECT on PROGRESS.SUBJECT=SUBJECT.SUBJECT
	inner join PULPIT on SUBJECT.PULPIT=PULPIT.PULPIT
	inner join FACULTY on PULPIT.FACULTY=FACULTY.FACULTY
	inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP 
	where PROGRESS.NOTE between 6 and 8
	order by PROGRESS.NOTE

--ex4--
select PULPIT.PULPIT as Кафедра, isnull(TEACHER.TEACHER_NAME, '***') as Преподователь
from PULPIT left outer join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT

--ex5--
select ISNULL(PROGRESS.SUBJECT, '***') as Дисциплина, STUDENT.NAME as Имя, ISNULL(PROGRESS.NOTE,'-') as Оценка
from STUDENT full outer join PROGRESS
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
order by PROGRESS.SUBJECT

select ISNULL(PROGRESS.SUBJECT, '***') as Дисциплина, STUDENT.NAME as Имя, ISNULL(PROGRESS.NOTE,'-') as Оценка
from STUDENT full outer join PROGRESS
on PROGRESS.IDSTUDENT=STUDENT.IDSTUDENT 
order by PROGRESS.SUBJECT

select ISNULL(PROGRESS.SUBJECT, '***') as Дисциплина, STUDENT.NAME as Имя, ISNULL(PROGRESS.NOTE,'-') as Оценка
from STUDENT left outer join PROGRESS
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
order by PROGRESS.SUBJECT

select ISNULL(PROGRESS.SUBJECT, '***') as Дисциплина, STUDENT.NAME as Имя, ISNULL(PROGRESS.NOTE,'-') as Оценка
from STUDENT right outer join PROGRESS
on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
order by PROGRESS.SUBJECT

select count(*)
from STUDENT full outer join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.IDSTUDENT is null

select count(*)
from STUDENT left outer join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.IDSTUDENT is null

select count(*)
from STUDENT right outer join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.IDSTUDENT is null

--ex6--
select AUDITORIUM.AUDITORIUM,AUDITORIUM.AUDITORIUM_TYPE
	from AUDITORIUM_TYPE cross join AUDITORIUM
	where AUDITORIUM_TYPE.AUDITORIUM_TYPE = AUDITORIUM.AUDITORIUM_TYPE